# Generated by Django 5.2.7 on 2025-11-21 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('BENEFICIARY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='Testator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='testator_id/')),
                ('death_certificate', models.FileField(blank=True, null=True, upload_to='death_certificate/')),
                ('deceased_date', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deceased', 'Deceased')], default='active', max_length=20)),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='hash_checking/')),
                ('result', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Will_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='will_document/')),
                ('description', models.CharField(max_length=255)),
                ('encryption_key', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('TESTATOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testator')),
            ],
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='WILL_DOCUMENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.will_document'),
        ),
    ]
