# Generated by Django 5.2.7 on 2025-11-21 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_testator_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='will_document',
            name='password',
        ),
        migrations.RemoveField(
            model_name='will_document',
            name='username',
        ),
        migrations.AddField(
            model_name='will_document',
            name='USER',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
