# Generated by Django 5.2.7 on 2025-11-21 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_will_document_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='BENEFICIARY',
        ),
        migrations.AddField(
            model_name='notification',
            name='WILL_DOCUMENT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.will_document'),
            preserve_default=False,
        ),
    ]
